### ISSUE TITLE
Other available attributes

### ISSUE THREAD

**Issue by elfha** [epool86/calculateshopee#6]
Salam bang, 
kalau macam attribute2 quantity, product category, order date ada ke bang? 
Apa lagi attribute yg available utk di explore?

Tq for the fruitful code sharing :D

**Comment by epool86** [comment]
Wslm, sebenarnya banyak data yang diberi. Ini json yang Shopee return untuk 1 order.

`{
    "status": {
        "status_label": {
            "text": "label_order_completed",
            "tl": false
        },
        "header_text": {
            "text": "order_status_text_completed_thank_you_shopping",
            "tl": false
        },
        "header_image": "https://deo.shopeemobile.com/shopee/shopee-orderprocessing-live-my/completed.png",
        "list_view_text": {
            "text": "order_list_text_completed_enabled_buyer_has_rated_cannot_edit_seller_has_not_rated_cannot_rate",
            "tl": false
        },
        "list_view_status_label": {
            "text": "label_rated",
            "tl": false
        }
    },
    "shipping": {
        "tracking_info": {
            "driver_phone": "",
            "driver_name": "",
            "ctime": 1634274761,
            "description": "Parcel has been delivered",
            "type": 0
        },
        "is_multi_parcel": false,
        "num_parcels": 1,
        "parcel_no": 1
    },
    "info_card": {
        "order_id": 87865905374245,
        "order_list_cards": [
            {
                "shop_info": {
                    "shop_id": 724335,
                    "shop_name": "Dasher",
                    "user_id": 724835,
                    "username": "dasher",
                    "portrait": "36aeb0b111e28e266ee63edcf99b2609",
                    "shop_tag": 1
                },
                "items": [
                    {
                        "item_id": 11348163331,
                        "model_id": 130382009628,
                        "shop_id": 724335,
                        "name": "[Global Version] Smart Home Voice Assist Alarm Clock AI Touch Screen Speaker with Google Assistant",
                        "model_name": "",
                        "image": "44cd5f3e1ece3c84caaea729481af905",
                        "amount": 1,
                        "status": 2,
                        "item_price": 24500000,
                        "order_price": 24500000,
                        "snapshot_id": 3002269029
                    }
                ],
                "order_id": 87865905374245,
                "parcel_cards": [
                    {
                        "parcel_no": 1,
                        "forder_id": "4748128960249857335",
                        "product_info": {
                            "item_groups": [
                                {
                                    "items": [
                                        {
                                            "item_id": 11348163331,
                                            "model_id": 130382009628,
                                            "shop_id": 724335,
                                            "name": "[Global Version] Smart Home Voice Assist Alarm Clock AI Touch Screen Speaker with Google Assistant",
                                            "model_name": "",
                                            "image": "44cd5f3e1ece3c84caaea729481af905",
                                            "amount": 1,
                                            "ext_info": {
                                                "add_on_deal_id": 0,
                                                "is_add_on_sub_item": false,
                                                "free_return_day": 0,
                                                "is_wholesale": false,
                                                "is_pre_order": false
                                            },
                                            "status": 2,
                                            "item_price": 24500000,
                                            "order_price": 24500000,
                                            "snapshot_id": 3002269029
                                        }
                                    ],
                                    "num_items": 1
                                }
                            ],
                            "total_num_items": 1
                        }
                    }
                ]
            }
        ],
        "product_count": 1,
        "subtotal": 24960000,
        "final_total": 24960000
    },
    "primary_buttons": [
        {
            "id": 24
        }
    ],
    "guarantee": {
        "learn_more_url": "https://help.shopee.com.my/my/s/article/What-is-Shopee-Guarantee-How-does-it-work-1542969804788",
        "is_extend_enabled": true
    },
    "misc": {
        "urls": {
            "guarantee_learn_more": "https://help.shopee.com.my/my/s/article/What-is-Shopee-Guarantee-How-does-it-work-1542969804788"
        }
    },
    "secondary_buttons": [
        {
            "id": 15
        },
        {
            "id": 11
        }
    ],
    "list_type": 3
}`

**Comment by elfha** [comment]
wow okay baik.. terima kasih banyak
